### ISSUE TITLE
Please add support for the iPad pro smart keyboard arrow keys

### ISSUE THREAD

**Issue by JamesOwers** [hackmdio/hackmd-io-issues#80] opened 2019-03-08 21:41 UTC
Using an iPad Pro, and HackMD in a browser: depressing the arrow keys on the official keyboard has no effect. This is a shame since it means I have to keep navigating using my finger on the screen. This is inconvenient and means I may as well just use the onscreen keyboard.

Other editors, such as the one I'm using now on GitHub support the arrow keys fine, allowing me to navigate quickly with shortcuts etc.

**Comment by Felixmil** [comment] 2019-06-16 20:58
I started using HackMD two days ago as it fills all of my needs and thank you so much for making it possible 🙏

One of them is to write from my iPad using my Bluetooth keyboard.  Unfortunately, it is impossible to use arrows keys and selecting, copy pasting is also terrible. I tried with a lot of different browsers (safari, Firefox, opera...), same problem in all of them while everything was ok on stackedit or other apps.

It looks like the iPad does not consider it a text, weird... Would be fantastic if you cool fix that ! 

Thanks.

**Comment by jackycute** [comment] 2019-06-17 00:54
Hi all,
Please upgrade to iOS 13, it seems fixed the arrow keys bug.

**Comment by Felixmil** [comment] 2019-06-17 07:55
As not a developper, iOS 13 beta will only be available in July, cannot test it. But thanks !

**Comment by jackycute** [comment] 2019-06-26 02:28
Here is the official bug tracker.

https://bugs.webkit.org/show_bug.cgi?id=149054

**Comment by Yukaii** [comment] 2019-09-25 13:34
iOS 13.1 and iPadOS 13.1 are out! Please give it a try to see if you still encounter this issue!

**Comment by niklas-heer** [comment] 2019-09-26 05:10
@Yukaii I can confirm this now works with iPadOS 13.1 with the Smart Keyboard and also external bluetooth keyboards. Other navigation shortcuts like `CMD + arrow key` also work.

https://dsc.cloud/nheer/Movie-2019-09-26-07-05.mov

Bonus: It also works with an external bluetooth keyboard and iOS 13.1.

**Comment by Yukaii** [comment] 2019-09-26 15:50
@niklas-heer Thanks for confirming this. Close this issue now 🎉

**Closed by Yukaii** 2019-09-26 15:50 UTC
